apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: hf06arpti-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:6a8c044217ce462b523fc15a4692269933ef8f3e@sha256:07b0cff46475a0ac9d4586d5ba2c932592195c0c012411937ff4834e635db702
        name: container-image  
